version: '3'

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
        - ./backend:/var/www
    ports:
      - 8000
    working_dir: /var/www
    command: cargo run

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000
    depends_on:
      - backend
    working_dir: /app
    command: npm run dev
