import { GetServerSidePropsContext, GetServerSidePropsResult } from "next";
import Head from "next/head";
import { getSsrData, syncSession } from "../client";

type Props = {
  title?: string;
  num?: number;
  sessionId: string;
};

function Ssr({ title, num, sessionId }: Props) {
  return (
    <div>
      <Head>
        <title>SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>{title}</h2>
      <div>
        <h4>num</h4>
        <div>{num}</div>
      </div>
      <div>
        <h4>sessionId</h4>
        <div>{sessionId}</div>
      </div>
    </div>
  );
}

export async function getServerSideProps(
  context: GetServerSidePropsContext
): Promise<GetServerSidePropsResult<Props>> {
  const cookie = await syncSession(context);
  const a = await getSsrData(context);
  return {
    props: {
      title: a["title"],
      num: Number(a["num"]),
      sessionId: cookie,
    },
  };
}

export default Ssr;
