import { GetServerSideProps } from "next";
import Head from "next/head";
import { getSsrData } from "../client";

// propsの型を定義する
type Props = {
  title?: string;
  num?: number;
};

function Ssr({ title, num }: Props) {
  return (
    <div>
      <Head>
        <title>SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>{title}</h2>
      <div>
        <span>num</span>
        <span>{num}</span>
      </div>
    </div>
  );
}

export default Ssr;

export async function getServerSideProps(context: GetServerSideProps) {
  const a = await getSsrData();
  return {
    props: {
      title: a["title"],
      num: Number(a["num"]),
    },
  };
}
